# Generated by Django 5.2.4 on 2025-07-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_skill_user_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='university_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
