# Generated by Django 5.2.4 on 2025-07-27 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_goal_user_remove_skill_user_goal_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='profiles.profile'),
        ),
    ]
