# Generated by Django 5.2.4 on 2025-07-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_goal_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
