# Generated by Django 5.2.4 on 2025-07-28 08:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_initiated', to='profiles.profile')),
                ('profile2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_received', to='profiles.profile')),
            ],
        ),
    ]
