# Generated by Django 5.2.4 on 2025-07-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profile_created_at_connection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='career',
            new_name='major_uni',
        ),
    ]
