# Generated by Django 5.2.4 on 2025-07-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_profile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
