# Generated by Django 5.2.4 on 2025-08-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_connection_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='accepted',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
