# Generated by Django 5.2.4 on 2025-08-04 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_connection_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_score', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('recommended_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_to', to='profiles.profile')),
            ],
        ),
    ]
