# Generated by Django 5.2.4 on 2025-08-04 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_userrecommendation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRecommendation',
            new_name='UserAlumniRecommendation',
        ),
    ]
