# Generated by Django 5.2.4 on 2025-08-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_rename_userrecommendation_useralumnirecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralumnirecommendation',
            name='compatibility_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='useralumnirecommendation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
