# Generated by Django 5.2.4 on 2025-08-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_alter_useralumnirecommendation_compatibility_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='send_digest_email',
            field=models.BooleanField(default=True),
        ),
    ]
