# Generated by Django 5.2.4 on 2025-09-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_profile_send_digest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
