# Generated by Django 5.2.4 on 2025-07-21 15:57

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_groups_remove_groupmessage_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='group',
            field=models.ForeignKey(default=shortuuid.main.ShortUUID.uuid, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='messaging.groups', unique=True),
        ),
    ]
