# Generated by Django 5.2.4 on 2025-07-21 17:05

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_members_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='messaging.groups'),
        ),
    ]
