# Generated by Django 5.2.4 on 2025-07-24 15:34

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_alter_groups_group_name_alter_members_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=255, unique=True),
        ),
    ]
