# Generated by Django 5.2.4 on 2025-08-14 20:00

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0031_members_last_read_message_messages_is_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='last_read_message',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='is_read',
        ),
        migrations.AlterField(
            model_name='groups',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=255, unique=True),
        ),
    ]
