# Generated by Django 5.2.4 on 2025-08-16 06:29

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0032_remove_members_last_read_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='last_seen',
        ),
        migrations.AddField(
            model_name='members',
            name='last_read_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=255, unique=True),
        ),
    ]
