# Generated by Django 5.2.4 on 2025-08-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_system', models.CharField(choices=[('OptimisedAlgorithm', 'OptimisedAlgorithm'), ('SimpleAlgorithm', 'SimpleAlgorithm'), ('UnoptimisedAlgorithm', 'UnoptimisedAlgorithm')], default='SimpleAlgorithm', max_length=200)),
            ],
        ),
    ]
