# Generated by Django 5.2.4 on 2025-08-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recommendationsystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationsystem',
            name='recommendation_system',
            field=models.CharField(choices=[('OptimisedAlgorithm', 'OptimisedAlgorithm'), ('SimpleAlgorithm', 'SimpleAlgorithm'), ('None', 'None')], default='SimpleAlgorithm', max_length=200),
        ),
    ]
