# Generated by Django 5.2.4 on 2025-07-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='MentorSkills',
        ),
    ]
