# Generated by Django 5.2.4 on 2025-08-03 09:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_rename_skills_mentorskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentormatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
