# Generated by Django 5.2.4 on 2025-07-17 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_languages_mentor_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languages',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='user',
        ),
        migrations.AddField(
            model_name='languages',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='alumni.mentor'),
        ),
        migrations.AddField(
            model_name='skills',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='alumni.mentor'),
        ),
    ]
