# Generated by Django 5.2.4 on 2025-07-17 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_remove_languages_user_remove_skills_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='availability',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='languages',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='alumni.mentor'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='alumni.mentor'),
        ),
    ]
