# Generated by Django 5.2.4 on 2025-07-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_mentor_availability_alter_languages_mentor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
