# Generated by Django 5.2.4 on 2025-07-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_mentormatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentormatch',
            name='accept',
            field=models.BooleanField(default=None),
        ),
    ]
