# Generated by Django 5.2.4 on 2025-07-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0008_mentormatch_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentormatch',
            name='accept',
            field=models.BooleanField(null=True),
        ),
    ]
