# Generated by Django 5.2.4 on 2025-07-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0009_alter_mentormatch_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentormatch',
            name='accept',
            field=models.BooleanField(),
        ),
    ]
