# Generated by Django 5.2.4 on 2025-07-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0012_mentormatch_accept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentormatch',
            name='accept',
        ),
    ]
