# Generated by Django 5.2.4 on 2025-07-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0013_remove_mentormatch_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentormatch',
            name='accept',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
