# Generated by Django 5.2.4 on 2025-07-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0014_mentormatch_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
