# Generated by Django 5.2.4 on 2025-07-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0015_profile_employer_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_job',
            field=models.BooleanField(null=True),
        ),
    ]
